### ISSUE TITLE
Please bring back keepalive option

### ISSUE THREAD

**Issue by nwoltman** [webpack/grunt-webpack#102]
The `keepalive` option was recently removed in 91fcfec45640c9ac684fa1740c26d34fedd965a2. I would like to request that it be brought back because it is necessary to be able to run other tasks after the initial build is complete such as starting an Express server or watching other files with watch/chokidar.

**Comment by danez** [comment]
Sorry, that I conflict with your usecase. I can see what you are needing this option for, but I'm not sure if it is the job of the webpack plugin to keep the grunt process alive. If you use the webpack plugin for watching grunt, or using dev-server it should stay alive, but for a simple normal run it isn't.

You could use [grunt-keepalive](https://github.com/noamokman/grunt-keepalive) or maybe the express plugin you use can keep the process alive.

I don't want to block this completely, but want to ensure it is not just there for non webpack related stuff which could be done with other plugins. More options also make the code and the option handling more complicated.

What do you think?

**Comment by nwoltman** [comment]
Thanks for listening to my situation. Based on your feedback, I think I should have been more clear about my use case. I actually don't want the webpack task to keep the grunt process alive.

With the `keepalive` option gone, now when `watch` is `true` or when using the `webpack-dev-server` task, it is as though `keepalive` is always `true`, but I actually want it to be `false` so that I can run other grunt tasks afterward. Here's a simplified version of my Gruntfile:

```js
grunt.initConfig({
  webpack: {
    build: {
      // normal build
    },
  },

  'webpack-dev-server': {
    dev: {
      webpack: {
        // mostly the same as webpack:build
      },
      inline: true,
      // keepalive: false, // <- need this
    },
  },

  express: {
    // starts Express server in the background
  },

  chokidar: {
    express: { // restart Express when app, controllers, models, etc. change
      files: ['app.js', 'api/**/*.js'],
      tasks: 'express',
      options: {
        livereload: true,
        spawn: false,
      },
    },
  },
});

grunt.registerTask('build', ['webpack']);
grunt.registerTask('dev', ['webpack-dev-server', 'express', 'chokidar']);
```

Without being able to set `keepalive: false`, the grunt task will never get to the `'express'` or `'chokidar'` steps because the `'webpack-dev-server'` step blocks the whole task.

**Comment by nwoltman** [comment]
Thank you! 😃
