### ISSUE TITLE
"Invalid configuration object" error when running webpack-dev-server task

### ISSUE THREAD

**Issue by nwoltman** [webpack/grunt-webpack#104]
The `'webpack-dev-server'` task always fails because of an "Invalid configuration object" error:
`"configuration has an unknown property 'cache'."`

### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)

```js
grunt.initConfig({
  "webpack-dev-server": {
    // does not contain "cache" property anywhere
  }
});
```

### Expected Behavior
A webpack dev server should be started.

### Current Behavior
The following warning is printed to the console and the grunt process is aborted:

```
Warning: Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'cache'. These properties are valid:
   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? } Use --force to continue.
```

### Possible Solution
It looks like [this line](https://github.com/webpack/grunt-webpack/blob/master/src/options/OptionHelper.js#L95) is adding the `cache` property that is causing the warning.
Changing that line to this:

```js 
if ('cache' in result) {
  result.cache = false;
}
```

fixed the problem for me.

### Your Environment
| software         | version
| ---------------- | -------
| webpack          |  2.2.0-rc.0
| grunt-webpack | 2.0.0-beta.3
| grunt            | 1.0.1
| node             | 6.9.2
| npm              | 3.10.9
| Operating System | Windows 10

**Comment by danez** [comment]
Good catch. The whole dev-server for 2.0 is currently untested 😇
Fixing it now.

The line you mentioned was only meant to be for the webpack task not the dev-server

**Comment by danez** [comment]
Can you check if #105 fixes the problem?

**Comment by nwoltman** [comment]
Yes that fixes it 😃

**Comment by danez** [comment]
Sorry for all the troubles you have. I haven't gotten around to write integration tests for the dev-server (also not sure how to do that yet), so all the refactorings were a little bit risky.

I release a new version that fixes both things you brought up. Thanks again.

**Comment by nwoltman** [comment]
That's alright. Thanks for releasing a new version :)
