### ISSUE TITLE
webpack-dev-server options getting filtered erroneously

### ISSUE THREAD

**Issue by nwoltman** [webpack/grunt-webpack#106]
### Problem
The `hot` and `stats` options are not getting passed to the `webpack-dev-server` constructor.

### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)

```js
grunt.initConfig({
  "webpack-dev-server": {
    hot: true,
    // using default 'stats'
  }
});
```

### Expected Behavior
The `hot` and `stats` options should be passed to the webpack-dev-server constructor.

### Current Behavior
When I set the `hot` and `stats` options in my Gruntfile or if I leave them blank to use the default options (from [here](https://github.com/webpack/grunt-webpack/blob/master/src/options/default.js#L14-L24)), they are stripped out before being passed to the webpack-dev-server constructor ([here](https://github.com/webpack/grunt-webpack/blob/master/tasks/webpack-dev-server.js#L69)).

### Possible Solution
The options are getting filtered out by [this line](https://github.com/webpack/grunt-webpack/blob/master/src/options/OptionHelper.js#L91) because they are in the [`gruntOptions`](https://github.com/webpack/grunt-webpack/blob/master/src/options/default.js#L5) object.

I think `hot` (and `inline` as well) should be moved to the [`webpackDevServerOptions`](https://github.com/webpack/grunt-webpack/blob/master/src/options/default.js#L27) since they are not needed in the normal `webpack` task.

I'm not exactly sure what to do about `stats`. It could be added back after [this](https://github.com/webpack/grunt-webpack/blob/master/src/options/WebpackDevServerOptionHelper.js#L34) or it could be prevented from being filtered out [here](https://github.com/webpack/grunt-webpack/blob/master/src/options/OptionHelper.js#L91).

### Environment
| software         | version
| ---------------- | -------
| grunt-webpack | 2.0.0-beta.4

**Comment by danez** [comment]
Fixed in 2e191ffb1498c04ebb28555165df9a26b2ddcd31
