### ISSUE TITLE
webpack@1.x, required by grunt-webpack@1.0.18, is there a new grunt-webpack release coming, that uses webpack@2.x?

### ISSUE THREAD

**Issue by m-ahmadi** [webpack/grunt-webpack#110]
Currently grunt-webpack plugin uses webpack@1.x.
Is there a new release that uses webpack@2.x ?

**Comment by danez** [comment]
You can install the beta version of `grunt-webpack 2.0.0`

```
npm install grunt-webpack@beta
```
