### ISSUE TITLE
Webpack-Dev-Server: Default option for webpack context is invalid

### ISSUE THREAD

**Issue by sateffen** [webpack/grunt-webpack#114]
If using this plugin with webpack2, it won't build unless you specify a correct *context* property on the webpack configuration.

The problem is, that https://github.com/webpack/grunt-webpack/blob/master/src/options/default.js#L35 tells the default of *context* to be `'.'`, but according to the [documentation](https://webpack.js.org/configuration/entry-context/#context) the given path has to be absolute, not relative. That crashes the process:

```
TypeError: Cannot read property 'length' of undefined
  at getPaths (.../project/node_modules/enhanced-resolve/lib/getPaths.js:29:20)
```

### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)

Grunt config webpack-dev-server task with a webpack configuration without a *context* (or the *context* set to *undefined*)

### Expected Behavior
It should not set the default value to something wrong (currently `'.'`)

### Current Behavior
It should set nothing, or set something that fits the [documentation](https://webpack.js.org/configuration/entry-context/#context).

### Possible Solution
Set the default to *undefined*, just remove it, so the webpack compiler can determine its value on its own.

### Context
I'm porting build-tools from webpack1 to webpack2. The build configuration doesn't have a context set, because I want to use the default value (cwd).

### Your Environment

| software         | version
| ---------------- | -------
| webpack          |  beta
| grunt-webpack    | beta
| grunt            | 1.0.1
| node             | 7.4.0
| npm              | 4.1.1
| Operating System | Windows 7

**Comment by danez** [comment]
Good catch, can you make a PR and remove the default option?

**Comment by sateffen** [comment]
Added PR
