### ISSUE TITLE
Using caching with jshint

### ISSUE THREAD

**Issue by bjnortier** [webpack/grunt-webpack#28]
Is there a way to configure grunt-webpack to use caching (i.e. watch + keep alive), but only when a previous task has executed successfully?

I only want the webpack task to run when the jshint task has completed successfully. But it should also use the caching which results in much faster webpack executions.

**Comment by danez** [comment]
Is this still an issue? If yes could you create an example please.

**Comment by bjnortier** [comment]
I'm not using grunt anymore, so I'll close the issue
