### ISSUE TITLE
Split grunt-webpack and grunt-webpack-dev-server

### ISSUE THREAD

**Issue by Vijar** [webpack/grunt-webpack#29]
If I'm only going to use the `webpack` task, it seems unnecessary to enforce a peer-dep on `webpack-dev-server`.

@jrea

**Comment by callmemagnus** [comment]
I would really appreciate that...

I'm using grunt-webpack in CI and it introduces webpack-dev-server peerDependency that is impossible to install because of this issue https://github.com/Automattic/engine.io-client/issues/348.

Could this be on the agenda in a reasonable timeframe ?

**Comment by rubennorte** [comment]
I'd also appreciate that. For the moment I'm using the webpack node API directly from grunt, but it'd be nice to reduce the boilerplate using this package if it wouldn't include the webpack-dev-server.

My task, in case it's useful for anyone:

```javascript
  grunt.registerTask(
    'buildJs',
    function(mode) {
      var done = this.async();
      var config = require('../../resources/config/webpack.config');

      var handler = function(err, stats) {
        console.log(stats.toString({
          colors: true
        }));

        done(!err && !stats.hasErrors());
        done = function() {};
      };

      var compiler = webpack(config);
      if (mode === 'development') {
        compiler.watch(grunt.config('jsConfig.watchDelay'), handler);
      } else {
        compiler.run(handler);
      }
    });
```

**Comment by Moezalez** [comment]
I'd appreciate that. 
I don't use the web server at all, but the grunt task does not seem to work when the server module is not present.

**Comment by callmemagnus** [comment]
In the meantime, I created: https://www.npmjs.com/package/grunt-webpack-without-server

**Comment by joth** [comment]
+1. would be greatly appreciated

**Comment by pr1ntr** [comment]
+1.

**Comment by andresn** [comment]
@sokra  +1, our problem is `npm@3` stops installing peerDep

**Comment by BYK** [comment]
@sokra - what do we need to get this moving?

**Comment by hxgdzyuyi** [comment]
+1

**Comment by srhoulam** [comment]
+1

**Comment by sebastianhaas** [comment]
+1

**Comment by anton-suprunov** [comment]
+1

**Comment by danez** [comment]
This is done as of version 2.0.0-beta.1
