### ISSUE TITLE
"Circular reference detected" warning on watch

### ISSUE THREAD

**Issue by avaly** [webpack/grunt-webpack#32]
Using `grunt-webpack` 1.0.8, `webpack` 1.4.8, `extract-text-webpack-plugin` 0.3.3, `style-loader` 0.8.1, `css-loader` 0.9.0, `less-loader` 0.7.7, running `grunt-wepack` on a watch task, the first time the watch task triggers it compiles everything fine, but the second time the watch task triggers it throws the following warning and does not compile anything:

```
Running "webpack:dev" (webpack) task
Warning: Circular reference detected (.plugins[0].modulesByIdentifier["/src/project/node_modules/css-loader/index.js!/src/project/node_modules/less-loader/index.js!/src/project/ui/src/less/index.less"].chunks[0].modules[0])
```

This warning appeared after we bump a few dependencies on our project. Previously we had the following versions: `grunt-webpack` 1.0.8, `webpack` 1.4.4, `extract-text-webpack-plugin` 0.2.5, `style-loader` 0.7.0, `css-loader` 0.7.1, `less-loader` 0.7.7 and we didn't experience this warning on the same set of files.

Don't know exactly which module is responsible for this error, but since the error message is specific to grunt, I just post this here.

**Comment by shama** [comment]
@avaly Is this still an issue?

**Comment by avaly** [comment]
Unfortunately, I don't have access to the project which presented this issue. @alepek, can you please try this again?

**Comment by alepek** [comment]
@shama @avaly Using
`grunt-webpack` 1.0.11
`extract-text-webpack-plugin` 0.3.3
`style-loader` 0.8.1
`css-loader` 0.9.0
`less-loader` 0.7.7
`webpack` 1.4.8 **OR** 1.7.3

this issue is no longer present and subsequent watches that trigger grunt-webpack work fine.

**Comment by shama** [comment]
:+1: Thanks!
