### ISSUE TITLE
Can't use different configs in same time

### ISSUE THREAD

**Issue by huston007** [webpack/grunt-webpack#35]
I'm trying to use the next configuration:
```
webpack: {
     options: require('./node_modules/package1ToBuild/webpack.config.js'),
     package1: {
         //Specified options to override
     },
     package2: {
         //options: I can't use it for this task only!
         //Specified options for second package
     }
```

The task options is applied for all subtasks so I can't use it to build different packages with different options.

**Comment by grrowl** [comment]
Personally I do this:
```js
    webpack: {
      options: {},
      build: webpackConfig('prod'),
      'build-dev': webpackConfig('dev')
    },
```

webpackConfig (`= require('webpack.config')`) is a function which handles the config layering/merging, as I suspect you've implemented there.
