### ISSUE TITLE
`--inline` option from Grunt

### ISSUE THREAD

**Issue by unindented** [webpack/grunt-webpack#36]
Why isn't there an `inline` config option equivalent to the `--inline` CLI param?

I want to achieve the same effect as launching `webpack-dev-server --inline`, but from a Grunt task. I would need to add the two entry points manually (`['webpack-dev-server/client/index.js?http://localhost:8080', 'webpack/hot/dev-server']`, but it feels to me that's Webpack internals, and I shouldn't put that stuff in my task.

@sokra what do you think?

**Comment by jcreamer898** [comment]
Any updates on this? Would be a nice feature.

**Comment by sokra** [comment]
Easy to implement... Would you like to do a PR?

https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L106-L119

**Comment by jcreamer898** [comment]
Yessir. Will do.

**Comment by chiplay** [comment]
@sokra @jcreamer898 I'd love to get your feedback on my PR when you have a minute!

**Comment by unindented** [comment]
Yes please, really interested in this!

**Comment by jcreamer898** [comment]
Will have a look!

**Comment by unindented** [comment]
@sokra @jcreamer898 Any updates on this?

**Comment by jcreamer898** [comment]
Works perfect. Get that sucker merged. :)

**Comment by chiplay** [comment]
Merged: https://github.com/webpack/grunt-webpack/pull/41

**Comment by chiplay** [comment]
@unindented published 1.0.10 to npm with this patch

**Comment by unindented** [comment]
🎉🎉🎉

@chiplay Thank you!
