### ISSUE TITLE
Can I use text-replacement during serve and build...

### ISSUE THREAD

**Issue by dannymk** [webpack/grunt-webpack#38]
How do I replace a specific piece of code during the serve and build process.
Example:
original:  @@replace_this

dev:   http://localhost:8080/
build:  /?c=

It seems logical to create a configuration object then use a environment variable to specify either dev or build but I have no idea how to do this.  Can this be a grunt task such as:

https://www.npmjs.com/package/grunt-text-replace
https://github.com/outaTiME/grunt-replace

or am I looking at this the wrong way?
I am using generator-react-webpack which has a grunt task that creates a single application.js file during build.

Wish there was a list were I could ask this but I did not find one in the documentation.

**Comment by dannymk** [comment]
I did this by using grunt-rext-replace and changing the text once it was minimized in the dist/ then copying it to the target directory I wanted.  It works so I am keeping this solution and closing this issue.

**Comment by sokra** [comment]
`webpack.DefinePlugin` can do something similar to text replacing...

**Comment by dannymk** [comment]
working example?

**Comment by sokra** [comment]
here is the documentation: http://webpack.github.io/docs/list-of-plugins.html#defineplugin

**Comment by dannymk** [comment]
Ah, cool, thank you.
