### ISSUE TITLE
less task / grunt-webpack as grunt-less replacement

### ISSUE THREAD

**Issue by Phoscur** [webpack/grunt-webpack#4]
Maybe it's because I don't understand/like webpack's loaders, but I'd like to keep that task seperated from the JavaScript compiling.
Still, webpack leverages that ability to compile less files, so why shouldn't it be able to replace grunt-less?

grunt.js:

```
   webpack: {
          style: { src: "less/style.less", dest: "static/style.css" }
   }
```

**Comment by alexwasner** [comment]
This is still open. Is there a good solution for this?

**Comment by Phoscur** [comment]
@sokra provided a solution. Thanks for that! 
And sorry for not closing this earlier.
