### ISSUE TITLE
Production shortcut?

### ISSUE THREAD

**Issue by bestguy** [webpack/grunt-webpack#40]
Is there a way to use the production shortcut (https://webpack.github.io/docs/cli.html#production-shortcut-p) with grunt-webpack without manually specifying each plugin in the webpack.config.js or having two different config files?

I currently use one webpack.config.js for dev and production, and use `webpack -p` to build for production builds instead of specifying the production plugins.

**Comment by lostthetrail** [comment]
I think you will find people recommend you create a subtask which contains the shortcuts configuration manually.
