### ISSUE TITLE
Cannot read property 'loaders' of undefined

### ISSUE THREAD

**Issue by cdaringe** [webpack/grunt-webpack#43]
Hi all:

My config works via cmd line, but not via grunt-webpack.  Running `grunt webpack` renders:

```bash
Running tasks: webpack

Running "webpack" task

Running "webpack:main" (webpack) task
Verifying property webpack.main exists in config...OK
File: [no files]
Warning: Cannot read property 'loaders' of undefined Use --force to continue.
```

Tips?

##### works
`webpack --progress --colors`

##### does not work
`grunt webpack` with the following files
```js
module.exports = function (grunt) {
    grunt.loadNpmTasks("grunt-webpack");
    grunt.initConfig({
        webpack: {
            options: require('./webpack.config.js'),
            build: require('./webpack.config.js')
        }
    });
};
```
```js
var webpack = require('webpack');
var CommonsChunkPlugin = webpack.optimize.CommonsChunkPlugin;
var DedupePlugin = webpack.optimize.DedupePlugin;
var path = require('path');

module.exports = {
    entry: {
        tracker: './ampersand/app.js',
        main: './global-utils.js'
    },
    output: {
        path: path.join(__dirname + '/build', 'js'),
        filename: 'common.js'
    },
    plugins: [
        new DedupePlugin(),
        new CommonsChunkPlugin('global.js', ['tracker', 'main'])
    ]
};
```

**Comment by mareksimunek** [comment]
I had same error when I was using jade-loaders
```coffescript
        loaders: [
          test: /\.jade$/,
          loader: 'jade-loader'
        ]
```
I just downgraded to version 1.0.8 where it worked just fine.

**Comment by chiplay** [comment]
@cdaringe @mareksimunek looks like there was a reference to `options.module.loaders` added in https://github.com/webpack/grunt-webpack/commit/6ab5ea1e9f69cb506fcec3c5c9829b1cd2a68596, after the 1.0.8 tag.  When I push a new tag out recently, it picked up that change set as well.  

@roddeh @sokra Any thoughts on a fix?  Seems like a simple check for `options.module` might do the trick, I'm just not 100% sure what that changeset is doing and if there is anything else needed.

**Comment by jakiestfu** [comment]
What is `options.module` used for? It's undocumented.

**Comment by chiplay** [comment]
@jakiestfu I believe `options` in [this context](https://github.com/webpack/grunt-webpack/blob/master/tasks/webpack.js#L44) is simply the webpack config, in which case `module` is simply this: http://webpack.github.io/docs/configuration.html#module-loaders

**Comment by chiplay** [comment]
@jakiestfu possibly helpful: https://github.com/webpack/webpack-with-common-libs/blob/master/Gruntfile.js - which includes:

```
var webpackConfig = require("./webpack.config.js");
	grunt.initConfig({
		webpack: {
			options: webpackConfig,
                        ....
```

Where `options: webpackConfig` is simply the required webpack config object that has `module.loaders`

**Comment by cdaringe** [comment]
ya, adding 
```js
module: {
    loaders: []
}
```
at the same level as entry/output/etc did the trick, as is somewhat reasonable. thx

**Comment by muffinresearch** [comment]
Needing to set an empty list in config feels like a workaround to a bug to me. The patch (linked) should prevent the need to do that.

**Comment by cdaringe** [comment]
looks good

**Comment by almandsky** [comment]
This code should be more defensive?

https://github.com/webpack/grunt-webpack/blob/master/tasks/webpack.js#L44

Should check if the "options.module" exist before checking "options.module.loaders"?

**Comment by chiplay** [comment]
@almandsky @cdaringe closed with https://github.com/webpack/grunt-webpack/pull/44 - thanks @muffinresearch :tada:
