### ISSUE TITLE
module option must exist?

### ISSUE THREAD

**Issue by localnerve** [webpack/grunt-webpack#45]
Code introduced in b6507da85e4dfe8b4e3ed9dcee352043786d01fa makes the assumption that options.module is required or always exists at [this point](https://github.com/webpack/grunt-webpack/blob/5cb59aff1d9c088dfb53e8ab78b7e5b8054e3637/tasks/webpack.js#L44). I did not see support for this in the [webpack config doc](http://webpack.github.io/docs/configuration.html).

Caught me off guard. Most of my configs define loaders, but I have some simple ones too. Maybe this is a reasonable assumption?

Anyways, just ran into this, so documenting it forward. Thanks for this tool!

Just saw #43. That is the same issue as this. Can close if fixed.

**Comment by muffinresearch** [comment]
fwiw PR for #43 is here: https://github.com/webpack/grunt-webpack/pull/44

**Comment by chiplay** [comment]
Fixed and on npm as 1.0.11
