### ISSUE TITLE
build fails with an `resolve.alias` called `plugins`

### ISSUE THREAD

**Issue by Raigen** [webpack/grunt-webpack#48]
I am working on using webpack for our current project and came up with a strange bug in grunt-webpack.
We have a modular structure and some modules are called `plugins`. They are found in a subdirectory we resolved before with a requirejs configuration. Now with webpack I created an alias in `resolve.alias` like `plugins: 'source/plugins'`. With webpack used globally everything works fine, but when used with `grunt-webpack` I get a strange `undefined is not a function` error from grunt.
`grunt webpack --stack` prints out this (shortened):
```
Warning: undefined is not a function Use --force to continue.
TypeError: undefined is not a function
  at fixPlugins (C:\Users\foellerich\Git\epages-ui\node_modules\grunt-webpack\lib\getWithPlugins.js:25:31)
  at C:\Users\foellerich\Git\epages-ui\node_modules\grunt-webpack\lib\getWithPlugins.js:43:6
  at Array.forEach (native)
  at fixPlugins (C:\Users\foellerich\Git\epages-ui\node_modules\grunt-webpack\lib\getWithPlugins.js:41:21)
  at C:\Users\foellerich\Git\epages-ui\node_modules\grunt-webpack\lib\getWithPlugins.js:43:6
  at Array.forEach (native)
[...]
```
When renaming the alias at least this strange behavior is fixed. It seems as if the `fixPlugins`-method is crawling the whole config for the key `plugins` and then tries to resolve it as a plugin, even if it is just an alias.

**Comment by chiplay** [comment]
@Raigen you're right, [this code](https://github.com/webpack/grunt-webpack/blob/master/lib/getWithPlugins.js#L41) is doing exactly what your describe, walking the config tree recursively and looking for any `plugin` key.  I'm not sure exactly why its needed, or the best way to fix - maybe @sokra can chime in.

**Comment by maksimr** [comment]
+1 Have same issue but with configuration of svgo. svgo config contains property plugins, with list of strings. grunt task failing with error `Warning: Object prototype may only be an Object or null Use --force to continue.`

P.S.
Spent two hours realizing where problem.

**Comment by sokra** [comment]
Yeah, it's a bug. Only the `plugins` array of the webpack configuration should be affect.

grunt merges options by deep merge, which destroys the plugins instances. There this code restores the original plugins.

Feel free to send a PR fixing it. i. e. restrict it to top level `plugins`.

**Comment by maksimr** [comment]
@sokra please look at PR. I make changes based on example of config from README

Thanks

**Comment by maksimr** [comment]
ping

**Comment by maksimr** [comment]
@sokra @chiplay I still wait reply. It's really annoying bug
