### ISSUE TITLE
How do I enable the `display-error-details` flag?

### ISSUE THREAD

**Issue by uglymunky** [webpack/grunt-webpack#49]
Using grunt-webpack, how would I go about enabling the `display-error-details` flag?

**Comment by chiplay** [comment]
@uglymunky try adding `errorDetails: true` to your `stats` object in the config.  I haven't tested it, but seems like it might be the right way to go: http://webpack.github.io/docs/node.js-api.html#stats-tojson

**Comment by galeano** [comment]
@uglymunky were you able to figure this one out? I'm in desperate need to see a verbose version of errors and I can't figure out where to put this flag on. Thanks.

**Comment by uglymunky** [comment]
@galeano, sorry, I don't remember and I've since moved onto other stuff :/

**Comment by galeano** [comment]
@uglymunky No worries, thank you for replying.

**Comment by aromanyukvakoms** [comment]
thanks

**Comment by scottydawg** [comment]
@chiplay: yes, adding `errorDetails: true` to `stats` does provide verbose output. This might be worth noting in the main README as it's likely to help first-timers get the kinks worked out of their build. Especially since webpack error messages are pretty unfriendly, as noted by users [here](https://github.com/webpack/webpack/issues/981) and [here](https://github.com/webpack/karma-webpack/issues/33).

I was about 5 minutes away from going back to browserify before finding this thread.

**Comment by scottydawg** [comment]
Sample:

```js
    grunt.initConfig({      
      ...
      webpack: {
        app: {
          entry: 'target/.tmp/app.js',
          output: {
            path: 'target/dist/app',
            filename: 'app.bundle.js'
          },
          stats: {
            colors: true,
            modules: true,
            reasons: true,
            errorDetails: true
          },
          ...
        }
      }
      ...
```

**Comment by bergr01** [comment]
Adding the above stats snippets doesn't seem to produce anything meaningful for me, e.g.

>  [370] ./src/home/controller/home.controller.js 1.18 kB {1} [built]
 [371] ./src/modules/login/login.controller.js 1.56 kB {1} [built]
    + 351 hidden modules

**ERROR in undefined is not a function**
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules

**Comment by program247365** [comment]
It is most certainly this, just tried it:

Gruntfile.js:

```
// load grunt-webpack node_module
	grunt.loadNpmTasks('grunt-webpack');

	grunt.initConfig({
		webpack: require('./tasks/options/webpack.js')
	});
```

My ./tasks/options/webpack.js file:

```
var webpackConfig = require('../../webpack.config.js');

var webpack = require('webpack');

module.exports = {
	stats: {
		// Configure the console output
		errorDetails: true, //this does show errors
		colors: false,
		modules: true,
		reasons: true
	},
	progress: true,
	options: webpackConfig,
	build: {
		plugins: webpackConfig.plugins.concat(
			new webpack.DefinePlugin({
				"process.env": {
					// This has effect on the react lib size
					"NODE_ENV": JSON.stringify("production")
				}
			}),
			new webpack.optimize.DedupePlugin(),
			new webpack.optimize.UglifyJsPlugin()
		)
	},
	"build-dev": {
		devtool: "sourcemap",
		debug: true
	}
};
```

💫  ✨  😄

**Comment by danez** [comment]
I think this should not be a problem anymore
