### ISSUE TITLE
webpack-dev-server: default host option to "localhost" instead of undefined

### ISSUE THREAD

**Issue by WickyNilliams** [webpack/grunt-webpack#52]
Forgive me if i'm missing something obvious, but would it make more sense to set `host` option of the webpack-dev-server task to be "localhost"? 

I noticed all my socket.io connections for reloading were hitting `http://undefined/...` and couldn't work out why. Only when diving into task code did I see the problem. 

It's not obvious that you should combine `inline: true` with the host option, so setting a better default for host like a good idea.

**Comment by Oreqizer** [comment]
yep. keep debugging for like three days, till I found the issue. also there's more people not knowing what is going on:

http://stackoverflow.com/questions/31606533/webpack-transport-polling-errors

i'd suggest, when 'host' is not set, emit a warning, or set it to `localhost` as suggested

**Comment by danez** [comment]
Tis was fixed by #69
