### ISSUE TITLE
Looking for hot-update.json files in the wrong place

### ISSUE THREAD

**Issue by Jmeyering** [webpack/grunt-webpack#66]
I'm using a virtual machine to serve my webpack-dev-server and everything seems to be working just great except that the webpack-dev-server.js script trys to fetch my hot-update.json using my `window.location.hostname`, Rather than the ip address everything else is loaded from.

```
GET http://mysite.dev/b3ed7794aa51bd32ab93.hot-update.json 404 (Not Found)hotDownloadManifest @ bundle.js:26hotCheck @ bundle.js:224check @ dev-server.js:12(anonymous function) @ dev-server.js:56
dev-server.js:28 [HMR] Cannot find update. Need to do a full reload!
dev-server.js:29 [HMR] (Probably because of restarting the webpack-dev-server)
client:31 [WDS] Nothing changed.
```

When I check the virtual machine ip/port the hot update is there. `http://192.168.56.10:8080/0.e71cbe1b6f2760378f0d.hot-update.js`

How can I tell webpack to look for the hot update files at this location?

I'm embedding this script into my nginx served html page

```
<script src="http://192.168.56.10:8080/bundle.js"></script>
```

here is my webpack-dev-server.js  config file.

```
var webpack = require("webpack");
var webpackConfig = require("../webpack.config.js");
module.exports = {
    options: {
        webpack: webpackConfig,
        publicPath: "/",
    },
    default: {
        output: {
            publicPath: "http://192.168.56.10:8080/",
        },
        webpack: {
            devtool: "eval",
            debug: true,
        },
        host: "192.168.56.10",
        hot: true,
        inline: true,
        keepalive: true,
        watchOptions: {
            poll: 1000,
        },
    }
};


```

And in case its needed my webpack.config.js

```
var path = require("path");
var webpack = require("webpack");
module.exports = {
    cache: true,
    entry: {
        App: [
            path.join(__dirname, "assets/js/app.js"),
        ],
    },
    devtool: "cheap-module-source-map",
    output: {
        path: path.join(__dirname, "public/js"),
        filename: "bundle.js",
        sourceMapFilename: "[file].map",
    },
    module: {
        loaders: [
            {
                test: /\.scss$/,
                loaders: ["style", "raw", "sass"]
            },
            {
                test: /\.jsx?$/,
                exclude: /(node_modules)/,
                loader: "babel",
                query: {
                    plugins: ["transform-runtime"],
                    presets: ["es2015"],
                },
            },
        ],
    },
    resolve: {
        modulesDirectories: [
            "node_modules",
            "assets/js",
        ],
    },
    plugins: [],
};
```

**Comment by Jmeyering** [comment]
I was able to solve this by setting

```
 __webpack_public_path__ = "http://webpack:8080/";
```

In my entrypoint.

**Comment by Roomtailors** [comment]
Hey Jmeyering, I am having the same problem and with a very similar setup (vagrant etc.). Can you explain a bit more where you set this and how it takes effect. I am not sure how  __webpack_public_path__ = "http://webpack:8080/"; actually gets considered (if I put it in my entry.js it does nothing).

Thank you!

**Comment by Anarios** [comment]
I'm a bit late here, you need to add the line

`__webpack_public_path__ = "http://webpack:8080/"; `

into any .js file (main entry point for me is index.js)

**Comment by nickgcattaneo** [comment]
@Roomtailors => entry points in webpack can be very customized. e.g. starting from a typical webpack config object...
1. entry: "some/path/to/app.js"
2. entry: { myApp: "some/path/to/app.js" }
3. entry: [ 'somePreWrapperInjector', 'babel-polyfill', 'some/path/to/app.js' ]
4. entry: {
    app1: 'some/path/to/app1.js',
    app2: 'some/path/to/app2.js'
}
5. entry: {
    app1: [
        'somePreWrapperInjector', 'babel-polyfill', 'some/path/to/app1.js'
    ],
    app2: [
        'somePreWrapperInjector', 'babel-polyfill', 'some/path/to/app2.js'
    ]
}

These approaches allow basically for multiple entry points, any kind of prewrappers to your app, etc. In the case of how to inject the __webpack_public_path, it depends on what middleware you're using. Here's how I configure mine with webpack-hot-middleware, which is spun up in my own express server. If you don't want to deal with maintaining an express server, use webpack-dev-server instead:

webpackConfig.entry = [
	'babel-polyfill',
	'react-hot-loader/patch',
	'webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&reload=true&__webpack_public_path=http://webpack:' + config.port,
	dir.src.main.frontend.application.appEntry
]

Hope that helps.

**Comment by Roomtailors** [comment]
Thanks for the advice and help. With the improved understanding I have been able to operate hot reload in a vagrant-based dev server. If the full config is interesting let me now. I fire up the webpack-dev-server with the following command: 

`webpack-dev-server --watch-poll --content-base www/ --host 0.0.0.0 --port 8080`

**Comment by nojvek** [comment]
`__webpack_public_path__ = "http://webpack:8080/"` doesn't do anything for me.

**Comment by cheapsteak** [comment]
I'm explicitly setting `publicPath` (both in `config.devServer` and `config.output.devServer`) to an absolute `http://xxx.xxx.xxx` url, but the path for HMR it ends up using still contains the port number from its config.devServer.port (but no port was in the publicPath)

Have also tried doing `__webpack_public_path__ = "http://xxx.xxx.xxx" ` but the port is still there

**Comment by Hatimtech** [comment]
> `__webpack_public_path__ = "http://webpack:8080/"` doesn't do anything for me.

It worked after changing webpack to localhost

**Comment by jiricerhan** [comment]
Came across this issue lately, in my case it was caused by having the `output.publicPath` "relative" without domain and protocol. Fix was to use  `http://localhost:8080/web/dist` (full url) instead of `/web/dist`. Webpack HMR is trying to fetch hot-update.json just using the public path, ignoring `devServer.port` and `devServer.host`.
