### ISSUE TITLE
grunt-webpack adds double banner when bannerPlugin set in webpack.config.js

### ISSUE THREAD

**Issue by jlchereau** [webpack/grunt-webpack#73]
Same webpack.config.js with bannerPlugin, left file produced from ```grunt-webpack```, right file produced from ```webpack``` directly.

![image](https://cloud.githubusercontent.com/assets/2556751/15672273/9c732b84-2727-11e6-9290-aaca8676ce66.png)

grunt webpack is configured as follows:

```
webpack: {
    options: webpackConfig,
    build: {
        cache: false,
        plugins: webpackConfig.plugins.concat(
            new webpack.optimize.DedupePlugin(),
            new webpack.optimize.UglifyJsPlugin()
            // new webpack.optimize.AggressiveMergingPlugin() // Note: merges app.culture.fr.chunk.js
        )
    }
},
```

**Comment by danez** [comment]
Do you still have this problem? OR did you find a solution.

If you still have this problem please also submit the whole webpack config.
Currently I can not confirm this with a simple setup where BannerPlugin is added once.

**Comment by danez** [comment]
Close because of no response.
