### ISSUE TITLE
Fatal error: grunt.utils.merge is not a function 

### ISSUE THREAD

**Issue by mmmeff** [webpack/grunt-webpack#75]
Updated to 1.0.12 and I'm now seeing this fatal error when my build fails.

**Comment by mmmeff** [comment]
Reverting to 1.0.11 does resolve the issue

**Comment by danez** [comment]
Which fatal error?

**Comment by mmmeff** [comment]
See title(?)

**Comment by danez** [comment]
Thanks, I published again with a fix for that. Can you try 1.0.13?

**Comment by mmmeff** [comment]
You da man. That did the trick
