### ISSUE TITLE
What version of Webpack is being used.  That is not very clear here

### ISSUE THREAD

**Issue by xtianus79** [webpack/grunt-webpack#79]
To find the versions of your installed dependencies you can use `npm list webpack` and `npm list grunt-webpack`

That's it i don't know what version you are installing?  it isn't as transparent as you would think or is it just installing the latest one?

**Comment by sebastienbarre** [comment]
This is intended for Webpack 1.x, but I just noticed a recent `webpack2` [branch](https://github.com/webpack/grunt-webpack/tree/webpack2).

**Comment by danez** [comment]
grunt-webpack is not installing any version of webpack itself, but relies on people using grunt-webpack to install a suported version of webpack.
By supported I mean if using grunt-webapck 1.0, webpack 1.x is supported, and for grunt-webpack 2.0, webpack 2.0 is supported.

Hope that makes it more clear.
