### ISSUE TITLE
Ensure only valid webpack options are supplied to webpack

### ISSUE THREAD

**Issue by danez** [webpack/grunt-webpack#81]
Unfortunately it seems this plugin [is passing a `failOnError` option](https://github.com/webpack/grunt-webpack/blob/master/tasks/webpack.js#L29) that is now rejected by Webpack itself:
```
Warning: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'failOnError'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
```

Seems all options are passed to webpack right now, we need to separate between webpack options and grunt-plugin options.

**Comment by samtiffin** [comment]
I created a possible fix here: https://github.com/samtiffin/grunt-webpack/tree/split-webpack-options

(Sorry for not doing a pull request, I've not done it before so I didn't wanna mess it up and make extra work for you).

**Comment by danez** [comment]
Awesome 🎉 
The only thing to note is that instead of keeping a whitelist of valid options it would probably better to just filter out all options which we know are only for the grunt-plugin. This way we do not have to keep this list in sync with the main webpack repository, in the case options get renamed/added/deleted.

And feel free to do a PR. Your changes look perfectly fine to be done in a pull request. I would have noted the same in the PR as I did here (about the list of options), but this kind of feedback is not negative in any way, just trying to figure out the best possible solution. Also if you have a better idea, don't hesitate to correct me.
I also really appreciate that you are fixing this 👍, as I currently don't have time to look at it because I'm currently involved in a hackathon project at work.

If you need help with pull requests in general, have a look at the github docs [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) or feel free to ask here.

**Comment by samtiffin** [comment]
Good idea, I did have a look at using the schema parser that's being used in Webpack v2 to get the currently valid options but figured it'd mean even more complication (especially as it doesn't exist in webpack v1). I'll have a look a filtering out the grunt-plugin options and submit a pull request 👍.

**Comment by samtiffin** [comment]
Actually, thinking about it a bit more, a whitelist feels more appropriate here (even given the extra effort involved in maintaining it) as a user is able to enter any value into the config while creating the task (not just valid grunt-webpack config options) which the blacklist approach wouldn't catch. Admittedly it's a bit of an edge case, but one people might run into, it wasn't immediately obvious that all of the config options were being passed through to webpack.

The other option would be a bigger change and would involve specifying all webpack config under it's own key in the config object. It'd be a breaking change as the configuration interface would change but it would perhaps provide a bit more transparency about what's happening in the background?

**Comment by brianwyantora** [comment]
> The other option would be a bigger change and would involve specifying all webpack config under it's own key in the config object. It'd be a breaking change as the configuration interface would change but it would perhaps provide a bit more transparency about what's happening in the background?

+1.  I saw this issue when I tried to use webpack 2.x-betaY, while grunt-webpack is still on 1.x.  It makes sense to have a breaking version here along the same lines, marking the release(s) as 2.x-betaY until webpack is also out of beta.

**Comment by danez** [comment]
Fixed in 1.0.17

**Comment by danez** [comment]
Have to reopen as I had to revert the changes, as they are not compatible to webpack 1.0

**Comment by danez** [comment]
This is done in version 2.0.0-beta.1
