### ISSUE TITLE
Incorrect output filenames when configuration is an array

### ISSUE THREAD

**Issue by the-owl** [webpack/grunt-webpack#84]
When I've upgraded to grunt-webpack 1.0.15, passing array as a configuration object stopped working correctly. 1.0.14 is working fine.

I am passing an array that contains two sub-configs, and they have different `output.filename`. The problem is that in 1.0.15 only the first sub-config actually generates something, the second generates just the same file. So it seems that the second config is replaced with the first one, and the first one is just passed to webpack twice, causing it to generate the same file twice.

I'm using webpack 1.13.2 on Linux.

**Comment by danez** [comment]
Thanks for reporting, I have a look now.

**Comment by the-owl** [comment]
Thanks a lot! It works now.
