### ISSUE TITLE
Breaking change in latest version 1.0.17 ?

### ISSUE THREAD

**Issue by dharFr** [webpack/grunt-webpack#86]
Hi, 

The latest `grunt-webpack` release (`1.0.17`) has been breaking our build and we had to switch back to `1.0.16` to workaround the issue. 

For what I can tell, the update in 7d644daef7f52ec7e287f257c68058c79584698a breaks the `sass-loader` configuration options (see [sass-loader options](https://github.com/jtangelder/sass-loader#sass-options)) which requires an _invalid_ `sassLoader` option and then is ignored. 

I'm not sure about the original intent behind this update, but I suggest it should be reverted and eventually released again with a major version bump.

Cheers

**Comment by danez** [comment]
You are right sorry, reverted it. In webpack 2.0 this type of configuration is not allowed anymore. So might even consider already changing it now and instead using `query` param of the loader, so that in future you will have less problems.

**Comment by dharFr** [comment]
Thanks for the revert. 
I wasn't aware of that change in webpack 2. I'll definitely check the configuration options to prefer `query` parameters over specific options.

**Comment by danez** [comment]
Well I was just today also surprised that webpack 2.0 completely changed their config. So currently their is no way I think to have a hybrid 1.0/2.0 config

https://webpack.js.org/configuration/
