### ISSUE TITLE
Please make 'webpack-dev-server' an optional peer dependency

### ISSUE THREAD

**Issue by jennasalau** [webpack/grunt-webpack#87]
For projects such as ours we already have a dev server and will never use webpacks. 

It would be really great if we can make 'webpack-dev-server' an optional peer dependency so we don't have download it unnecessarily.

https://docs.npmjs.com/files/package.json#optionaldependencies

What do you think?

Thanks
Jenna

**Comment by danez** [comment]
Thanks for bringing that up. We already have an open ticket for that in #70 and we will definitely change that.

**Comment by jennasalau** [comment]
Great.. sorry i should have looked before opening. Feel free to close and ill watch that one.

Thanks.

**Comment by danez** [comment]
This is now done in version 2.0 for webpack 2.0
